import type { Brand, Product, Category, Review } from './types';

export const CATEGORIES: Category[] = [
  { id: 'fashion', name: 'Fashion', icon: 'Shirt', count: 1420, image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=600&q=80' },
  { id: 'electronics', name: 'Electronics', icon: 'Smartphone', count: 980, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80' },
  { id: 'beauty', name: 'Beauty & Wellness', icon: 'Sparkles', count: 650, image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80' },
  { id: 'furniture', name: 'Furniture & Home', icon: 'Armchair', count: 530, image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80' },
  { id: 'sports', name: 'Sports & Outdoors', icon: 'Dumbbell', count: 870, image: 'https://images.unsplash.com/photo-1517649763962-0c623266010b?auto=format&fit=crop&w=600&q=80' },
  { id: 'luxury', name: 'Luxury Goods', icon: 'Crown', count: 320, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80' },
  { id: 'automotive', name: 'Automotive Tech', icon: 'Car', count: 210, image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80' },
  { id: 'kids', name: 'Kids & Baby', icon: 'Baby', count: 410, image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=600&q=80' },
];

export const BRANDS: Brand[] = [
  {
    id: 'nike',
    name: 'Nike',
    slug: 'nike',
    logo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=150&q=80',
    coverImage: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=80',
    category: 'Sports & Fashion',
    rating: 4.9,
    reviewCount: 14200,
    productCount: 380,
    verified: true,
    description: 'Innovative footwear, apparel, and equipment designed to inspire world-class performance and everyday athleticism.',
    established: '1964',
    location: 'Beaverton, Oregon, USA',
    website: 'https://nike.com',
    socials: { instagram: '@nike', twitter: '@nike', facebook: 'nike' },
    featuredCollections: ['Air Max Series', 'Tech Fleece', 'Pro Training'],
    trending: true
  },
  {
    id: 'apple',
    name: 'Apple',
    slug: 'apple',
    logo: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=150&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    category: 'Electronics',
    rating: 4.95,
    reviewCount: 28400,
    productCount: 140,
    verified: true,
    description: 'Designed in California. Premium consumer electronics, software, and online services redefining human possibility.',
    established: '1976',
    location: 'Cupertino, California, USA',
    website: 'https://apple.com',
    socials: { twitter: '@apple', instagram: '@apple' },
    featuredCollections: ['Pro Ecosystem', 'Spatial Audio', 'Studio Display'],
    trending: true
  },
  {
    id: 'adidas',
    name: 'Adidas',
    slug: 'adidas',
    logo: 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=150&q=80',
    coverImage: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80',
    category: 'Sports',
    rating: 4.8,
    reviewCount: 9800,
    productCount: 290,
    verified: true,
    description: 'Through sport, we have the power to change lives. Leading German athletic footwear and apparel brand.',
    established: '1949',
    location: 'Herzogenaurach, Germany',
    website: 'https://adidas.com',
    socials: { instagram: '@adidas', twitter: '@adidas' },
    featuredCollections: ['Ultraboost', 'Originals Heritage', 'Y-3 Premium'],
    trending: true
  },
  {
    id: 'zara',
    name: 'Zara',
    slug: 'zara',
    logo: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=150&q=80',
    coverImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    category: 'Fashion',
    rating: 4.7,
    reviewCount: 7400,
    productCount: 520,
    verified: true,
    description: 'Global fashion leader bringing cutting-edge runaway trends and high fashion tailored for everyday wearability.',
    established: '1975',
    location: 'Arteixo, Spain',
    website: 'https://zara.com',
    socials: { instagram: '@zara' },
    featuredCollections: ['Origins Collection', 'Studio Edition', 'Tailored Luxe'],
    trending: false
  },
  {
    id: 'sony',
    name: 'Sony',
    slug: 'sony',
    logo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=150&q=80',
    coverImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80',
    category: 'Electronics',
    rating: 4.88,
    reviewCount: 11200,
    productCount: 180,
    verified: true,
    description: 'Pioneering sensory sound systems, studio cameras, OLED displays, and revolutionary gaming consoles.',
    established: '1946',
    location: 'Tokyo, Japan',
    website: 'https://sony.com',
    socials: { twitter: '@sony', instagram: '@sony' },
    featuredCollections: ['WH-1000XM Audio', 'Alpha Mirrorless', 'Bravia XR'],
    trending: true
  },
  {
    id: 'sephora',
    name: 'Sephora',
    slug: 'sephora',
    logo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=150&q=80',
    coverImage: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=80',
    category: 'Beauty',
    rating: 4.85,
    reviewCount: 15300,
    productCount: 450,
    verified: true,
    description: 'The world leader in luxury cosmetics, organic skincare serums, prestige fragrances, and beauty essentials.',
    established: '1969',
    location: 'Paris, France',
    website: 'https://sephora.com',
    socials: { instagram: '@sephora' },
    featuredCollections: ['Clean Beauty', 'Botanical Serums', 'Velvet Lipsticks'],
    trending: true
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Apple AirPods Max - Space Gray',
    brandId: 'apple',
    brandName: 'Apple',
    brandLogo: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=150&q=80',
    price: 549,
    originalPrice: 599,
    discountPercentage: 8,
    rating: 4.9,
    reviewCount: 2340,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'
    ],
    inStock: true,
    stockQuantity: 45,
    description: 'Apple-designed dynamic driver provides high-fidelity audio. Active Noise Cancellation with Transparency mode.',
    specifications: {
      'Audio Tech': 'Apple H1 Headphone Chip (each ear cup)',
      'Battery Life': 'Up to 20 hours listening time',
      'Connectivity': 'Bluetooth 5.0',
      'Weight': '384.8 grams'
    },
    colors: ['Space Gray', 'Silver', 'Sky Blue', 'Pink'],
    isTrending: true,
    isFlashSale: true,
    warranty: '1 Year AppleCare Warranty'
  },
  {
    id: 'p2',
    name: 'Nike Air VaporMax 2023 Flyknit',
    brandId: 'nike',
    brandName: 'Nike',
    brandLogo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=150&q=80',
    price: 210,
    originalPrice: 240,
    discountPercentage: 12,
    rating: 4.8,
    reviewCount: 1890,
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80'
    ],
    inStock: true,
    stockQuantity: 120,
    description: 'Walk on Air in the Nike Air VaporMax 2023. Stretchy Flyknit upper made with at least 20% recycled material by weight.',
    specifications: {
      'Cushioning': 'Continuous Air Unit',
      'Upper': 'Flyknit breathable mesh',
      'Closure': 'Lace-up',
      'Weight': '290 grams'
    },
    colors: ['Volt Yellow', 'Triple Black', 'Pure Platinum'],
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    isTrending: true,
    isFlashSale: false,
    warranty: '6 Months Manufacturer Guarantee'
  },
  {
    id: 'p3',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    brandId: 'sony',
    brandName: 'Sony',
    brandLogo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=150&q=80',
    price: 398,
    originalPrice: 420,
    discountPercentage: 5,
    rating: 4.92,
    reviewCount: 3100,
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
    inStock: true,
    stockQuantity: 60,
    description: 'Industry-leading noise canceling with two processors and 8 microphones for unprecedented sound purity.',
    specifications: {
      'Battery': '30 Hours playback',
      'Noise Cancellation': 'Dual Processor HD V1',
      'Microphones': '8 Beamforming Mics'
    },
    colors: ['Black', 'Silver', 'Midnight Blue'],
    isTrending: true,
    isFlashSale: true,
    warranty: '2 Year Sony Warranty'
  },
  {
    id: 'p4',
    name: 'Adidas Ultraboost Light Running Shoes',
    brandId: 'adidas',
    brandName: 'Adidas',
    brandLogo: 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=150&q=80',
    price: 190,
    originalPrice: 220,
    discountPercentage: 13,
    rating: 4.75,
    reviewCount: 940,
    category: 'sports',
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80'],
    inStock: true,
    stockQuantity: 80,
    description: 'Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever featuring 30% lighter Light BOOST material.',
    specifications: {
      'Midsole': 'Light BOOST cushioning',
      'Outsole': 'Continental Rubber',
      'Sustainability': '50% Parley Ocean Plastic'
    },
    colors: ['Cloud White', 'Core Black', 'Solar Red'],
    sizes: ['US 7.5', 'US 8.5', 'US 9.5', 'US 10.5'],
    isTrending: false,
    isFlashSale: false,
    warranty: '1 Year Adidas Warranty'
  },
  {
    id: 'p5',
    name: 'Zara Minimalist Oversized Trench Coat',
    brandId: 'zara',
    brandName: 'Zara',
    brandLogo: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=150&q=80',
    price: 159,
    originalPrice: 199,
    discountPercentage: 20,
    rating: 4.65,
    reviewCount: 420,
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80'],
    inStock: true,
    stockQuantity: 25,
    description: 'Double-breasted coat made of water-resistant cotton blend fabric. Lapel collar with long sleeves and epaulettes.',
    specifications: {
      'Material': '65% Cotton, 35% Polyamide',
      'Fit': 'Oversized Silhouette',
      'Care': 'Dry Clean Only'
    },
    colors: ['Sand Beige', 'Charcoal', 'Ecru'],
    sizes: ['S', 'M', 'L'],
    isTrending: true,
    isFlashSale: true,
    warranty: '30 Days Return Guarantee'
  },
  {
    id: 'p6',
    name: 'Sephora Glow Hydra-Serum Ritual',
    brandId: 'sephora',
    brandName: 'Sephora',
    brandLogo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=150&q=80',
    price: 88,
    originalPrice: 110,
    discountPercentage: 20,
    rating: 4.9,
    reviewCount: 1250,
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80'],
    inStock: true,
    stockQuantity: 200,
    description: 'Triple Hyaluronic Acid formula designed to restore moisture barrier and impart luminous glass-skin radiance within 7 days.',
    specifications: {
      'Key Ingredients': 'Hyaluronic Acid, Niacinamide 5%, Peptide Complex',
      'Skin Type': 'All Skin Types',
      'Volume': '50 ml / 1.7 fl oz'
    },
    colors: ['Clear'],
    isTrending: true,
    isFlashSale: false,
    warranty: 'Dermatologist Tested'
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Elena Rostova',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    date: 'August 2, 2026',
    title: 'Peak audio quality & immaculate build',
    comment: 'The noise cancellation on the AirPods Max is mind-blowing. Crisp spatial audio and seamless ecosystem integration across my Mac and iPad.',
    verifiedPurchase: true,
    helpfulVotes: 48,
    productName: 'Apple AirPods Max - Space Gray'
  },
  {
    id: 'r2',
    userName: 'Marcus Sterling',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    date: 'July 29, 2026',
    title: 'Best daily running shoes of the year',
    comment: 'VaporMax cushion feels weightless. Zero break-in period required. Highly recommend ordering true to size.',
    verifiedPurchase: true,
    helpfulVotes: 32,
    productName: 'Nike Air VaporMax 2023 Flyknit'
  }
];
